### PR TITLE
RBAC Error due to bad RBAC configs

### PR DESCRIPTION
**Pull request by ysaakpr**
`CRDS-RBAC` is missing the latest CRDs added.
By default, the RBAC need namespace permission else gives below error in the case of `scope enabled installation`.

> 2020-04-13 11:02:27 kubewatch [12 TMainThread] 1.4.0 DEBUG: looking up ID for namespace alpha2
2020-04-13 11:02:27 kubewatch [12 TMainThread] 1.4.0 ERROR: couldn't read namespace alpha2? (403)
Reason: Forbidden
HTTP response headers: HTTPHeaderDict({'Content-Type': 'application/json', 'X-Content-Type-Options': 'nosniff', 'Date': 'Mon, 13 Apr 2020 11:02:27 GMT', 'Content-Length': '334'})
HTTP response body: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"namespaces \"alpha2\" is forbidden: User \"system:serviceaccount:alpha2:ambassador-alpha2\" cannot get resource \"namespaces\" in API group \"\" in the namespace \"alpha2\"","reason":"Forbidden","details":{"name":"alpha2","kind":"namespaces"},"code":403}

### CODE REVIEW

**Comment by ysaakpr** [comment]
@kflynn  Please see this, will fix couple of errors happening due to RBAC configs

**Comment by ysaakpr** [comment]
Waiting for this merge, else leads to permission error while getting the cluster id and default to random id. What is the process here to get this merged? Am I missing something?

**Comment by nbkrause** [comment]
@ysaakpr Very sorry for letting this sit

Thanks for opening a PR to resolve this. The only comment I have is to bump the chart version to 6.3.3

**Comment by ysaakpr** [comment]
@nbkrause updates to 6.3.3

**Comment by ysaakpr** [comment]
Never mind, you can take your time,  we moved chart to our own chart repo. We have pushed our prod release for 3 weeks to merge this, can't wait anymore. 
Thank you

**Comment by nbkrause** [comment]
ysaakpr I am very sorry for the delay this merge has caused it is unacceptable for this project and we will work to improve our process of reviewing and merging PRs.

**Comment by ysaakpr** [comment]
Thank you very much, I can be a maintainer if given permission.

**Pull request merged**
